// import 'dart:io';

// import 'package:creafton_financial_services/screens/borrowers/borrower.dart';
// import 'package:creafton_financial_services/services/reports/pdf/pdf_borrowers_table.dart';
// import 'package:creafton_financial_services/services/reports/pdf/pdf_expenses_table.dart';
// import 'package:creafton_financial_services/services/reports/pdf/pdf_field_officers_table.dart';
// import 'package:creafton_financial_services/services/reports/pdf/pdf_footer.dart';
// import 'package:creafton_financial_services/services/reports/pdf/pdf_guarantors_table.dart';
// import 'package:creafton_financial_services/services/reports/pdf/pdf_header.dart';
// import 'package:creafton_financial_services/services/reports/pdf/pdf_loans_table.dart';
// import 'package:creafton_financial_services/services/reports/pdf/pdf_payments_table.dart';
// import 'package:creafton_financial_services/services/reports/pdf/report_summary.dart';
// import 'package:flutter/foundation.dart';
// import 'package:path_provider/path_provider.dart';
// import 'package:pdf/pdf.dart';
// import 'package:pdf/widgets.dart' as pw;


// // PDF Sections




// import '../../models/loan.dart';
// import '../../models/payment.dart';
// import '../../models/field_officer.dart';
// import '../../models/expenditure.dart';
// import '../../models/guarantor.dart';



// class ReportPdfGenerator {


//   static Future<File> generateReport({

//     required String reportTitle,


//     required List<Borrower> borrowers,


//     required List<Loan> loans,


//     required List<Payment> payments,


//     required List<FieldOfficer> fieldOfficers,


//     required List<Expenditure> expenses,


//     required List<Guarantor> guarantors,


//     String? generatedBy,


//   }) async {



//     final pdf = pw.Document();




//     pdf.addPage(


//       pw.MultiPage(


//         pageFormat: PdfPageFormat.a4,


//         margin: const pw.EdgeInsets.all(30),



//         header: (context) {


//           return PdfHeader.build(

//             title: reportTitle, reportTitle: '', generatedAt: null,

//           );

//         },



//         footer: (context) {


//           return PdfFooter.build(

//             context,

//           );

//         },




//         build: (context) {



//           return [



//             pw.SizedBox(

//               height: 15,

//             ),




//             pw.Text(

//               "Generated By: ${generatedBy ?? "System"}",

//               style: const pw.TextStyle(

//                 fontSize: 9,

//               ),

//             ),




//             pw.SizedBox(

//               height: 10,

//             ),





//             PdfSummarySection.build(


//               borrowers: borrowers,


//               loans: loans,


//               payments: payments,


//               expenses: expenses,


//             ),




//             pw.SizedBox(

//               height: 20,

//             ),





//             if (borrowers.isNotEmpty) ...[


//               _sectionTitle(

//                 "Borrowers",

//               ),



//               PdfBorrowersTable.build(

//                 borrowers,

//               ),



//               pw.SizedBox(

//                 height: 20,

//               ),

//             ],





//             if (loans.isNotEmpty) ...[


//               _sectionTitle(

//                 "Loans",

//               ),



//               PdfLoansTable.build(

//                 loans,

//               ),



//               pw.SizedBox(

//                 height: 20,

//               ),

//             ],





//             if (payments.isNotEmpty) ...[


//               _sectionTitle(

//                 "Payments",

//               ),



//               PdfPaymentsTable.build(

//                 payments,

//               ),



//               pw.SizedBox(

//                 height: 20,

//               ),

//             ],






//             if (fieldOfficers.isNotEmpty) ...[


//               _sectionTitle(

//                 "Field Officer Performance",

//               ),



//               PdfFieldOfficersTable.build(

//                 fieldOfficers,

//               ),



//               pw.SizedBox(

//                 height: 20,

//               ),

//             ],






//             if (expenses.isNotEmpty) ...[


//               _sectionTitle(

//                 "Expenses",

//               ),



//               PdfExpensesTable.build(

//                 expenses,

//               ),



//               pw.SizedBox(

//                 height: 20,

//               ),

//             ],






//             if (guarantors.isNotEmpty) ...[


//               _sectionTitle(

//                 "Guarantors",

//               ),



//               PdfGuarantorsTable.build(

//                 guarantors,

//               ),

//             ],


//           ];

//         },


//       ),


//     );





//     final directory =

//         await getApplicationDocumentsDirectory();





//     final reportDirectory = Directory(

//       "${directory.path}/Creafton Reports",

//     );





//     if (!await reportDirectory.exists()) {


//       await reportDirectory.create(

//         recursive: true,

//       );


//     }






//     final fileName =

//         "${reportTitle.replaceAll(" ", "_")}_"

//         "${DateTime.now().millisecondsSinceEpoch}"

//         ".pdf";






//     final file = File(

//       "${reportDirectory.path}/$fileName",

//     );





//     await file.writeAsBytes(

//       await pdf.save(),

//     );





//     return file;

//   }








//   static pw.Widget _sectionTitle(

//     String title,

//   ) {


//     return pw.Padding(


//       padding:

//           const pw.EdgeInsets.only(

//         bottom: 8,

//       ),



//       child: pw.Text(


//         title,

//         style: pw.TextStyle(

//           fontSize: 14,

//           fontWeight:

//               pw.FontWeight.bold,

//         ),


//       ),


//     );

//   }



// }