// import 'package:flutter/material.dart';

// import '../../../models/field_officer.dart';
// import '../../../services/field_officer_service.dart';

// class AddFieldOfficerScreen extends StatefulWidget {
//   const AddFieldOfficerScreen({super.key});

//   @override
//   State<AddFieldOfficerScreen> createState() => _AddFieldOfficerScreenState();
// }

// class _AddFieldOfficerScreenState extends State<AddFieldOfficerScreen> {
//   final _formKey = GlobalKey<FormState>();

//   final FieldOfficerService _service = FieldOfficerService();

//   final nameController = TextEditingController();

//   final phoneController = TextEditingController();

//   final nationalIdController = TextEditingController();

//   final districtController = TextEditingController();

//   final addressController = TextEditingController();

//   bool saving = false;

//   Future<void> saveOfficer() async {
//     if (!_formKey.currentState!.validate()) {
//       return;
//     }

//     setState(() {
//       saving = true;
//     });
//     try {
//       final officer = FieldOfficer(
//         // generated by service
//         officerNumber: "",

//         fullName: nameController.text.trim(),

//         phone: phoneController.text.trim(),

//         nationalId: nationalIdController.text.trim(),

//         district: districtController.text.trim(),

//         address: addressController.text.trim(),

//         status: "ACTIVE",
//         createdAt: DateTime.now().toIso8601String(),
//       );
//       await _service.createFieldOfficer(officer);

//       if (!mounted) return;
//       ScaffoldMessenger.of(context).showSnackBar(
//         const SnackBar(content: Text("Field officer created successfully")),
//       );

//       Navigator.pop(context);
//     } catch (e) {
//       ScaffoldMessenger.of(
//         context,
//       ).showSnackBar(SnackBar(content: Text(e.toString())));
//     } finally {
//       setState(() {
//         saving = false;
//       });
//     }
//   }

//   @override
//   Widget build(BuildContext context) {
//     return Scaffold(
//       appBar: AppBar(title: const Text("Add Field Officer")),

//       body: SingleChildScrollView(
//         padding: const EdgeInsets.all(16),

//         child: Form(
//           key: _formKey,

//           child: Column(
//             children: [
//               TextFormField(
//                 controller: nameController,

//                 decoration: const InputDecoration(
//                   labelText: "Full Name",

//                   prefixIcon: Icon(Icons.person),

//                   border: OutlineInputBorder(),
//                 ),

//                 validator: (value) {
//                   if (value == null || value.trim().isEmpty) {
//                     return "Enter full name";
//                   }

//                   return null;
//                 },
//               ),
//               const SizedBox(height: 15),
//               TextFormField(
//                 controller: phoneController,

//                 keyboardType: TextInputType.phone,

//                 decoration: const InputDecoration(
//                   labelText: "Phone Number",

//                   prefixIcon: Icon(Icons.phone),

//                   border: OutlineInputBorder(),
//                 ),

//                 validator: (value) {
//                   if (value == null || value.trim().isEmpty) {
//                     return "Enter phone number";
//                   }

//                   return null;
//                 },
//               ),
//               const SizedBox(height: 15),
//               TextFormField(
//                 controller: nationalIdController,

//                 decoration: const InputDecoration(
//                   labelText: "National ID",

//                   prefixIcon: Icon(Icons.badge),

//                   border: OutlineInputBorder(),
//                 ),
//               ),

//               const SizedBox(height: 15),

//               TextFormField(
//                 controller: districtController,

//                 decoration: const InputDecoration(
//                   labelText: "District",

//                   prefixIcon: Icon(Icons.location_city),

//                   border: OutlineInputBorder(),
//                 ),
//               ),

//               const SizedBox(height: 15),

//               TextFormField(
//                 controller: addressController,

//                 maxLines: 3,

//                 decoration: const InputDecoration(
//                   labelText: "Address",

//                   prefixIcon: Icon(Icons.home),

//                   border: OutlineInputBorder(),
//                 ),
//               ),

//               const SizedBox(height: 30),

//               SizedBox(
//                 width: double.infinity,

//                 height: 50,

//                 child: ElevatedButton(
//                   onPressed: saving ? null : saveOfficer,

//                   child: saving
//                       ? const CircularProgressIndicator()
//                       : const Text("Save Officer"),
//                 ),
//               ),
//             ],
//           ),
//         ),
//       ),
//     );
//   }
// }

import 'package:flutter/material.dart';

import '../../../core/theme/app_colors.dart';
import '../../../models/field_officer.dart';
import '../../../services/field_officer_service.dart';

class AddFieldOfficerScreen extends StatefulWidget {
  const AddFieldOfficerScreen({super.key});

  @override
  State<AddFieldOfficerScreen> createState() => _AddFieldOfficerScreenState();
}

class _AddFieldOfficerScreenState extends State<AddFieldOfficerScreen> {
  final _formKey = GlobalKey<FormState>();

  final FieldOfficerService _service = FieldOfficerService();

  final nameController = TextEditingController();

  final phoneController = TextEditingController();

  final nationalIdController = TextEditingController();

  final districtController = TextEditingController();

  final addressController = TextEditingController();

  bool saving = false;

  @override
  void dispose() {
    nameController.dispose();

    phoneController.dispose();

    nationalIdController.dispose();

    districtController.dispose();

    addressController.dispose();

    super.dispose();
  }

  Future<void> saveOfficer() async {
    if (!_formKey.currentState!.validate()) {
      return;
    }

    setState(() {
      saving = true;
    });

    try {
      final officer = FieldOfficer(
        officerNumber: "",

        fullName: nameController.text.trim(),

        phone: phoneController.text.trim(),

        nationalId: nationalIdController.text.trim(),

        district: districtController.text.trim(),

        address: addressController.text.trim(),

        status: "ACTIVE",

        createdAt: DateTime.now().toIso8601String(),
      );

      await _service.createFieldOfficer(officer);

      if (!mounted) return;

      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(
          content: Text("Field officer created successfully"),

          backgroundColor: AppColors.success,
        ),
      );

      Navigator.pop(context);
    } catch (e) {
      ScaffoldMessenger.of(context).showSnackBar(
        SnackBar(
          content: Text(e.toString()),

          backgroundColor: AppColors.danger,
        ),
      );
    } finally {
      if (mounted) {
        setState(() {
          saving = false;
        });
      }
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: AppColors.background,

      appBar: AppBar(
        backgroundColor: AppColors.primaryBlue,

        foregroundColor: Colors.white,

        elevation: 0,

        title: const Text(
          "Add Field Officer",

          style: TextStyle(fontWeight: FontWeight.bold),
        ),
      ),

      body: Center(
        child: SingleChildScrollView(
          padding: const EdgeInsets.all(35),

          child: Container(
            constraints: const BoxConstraints(maxWidth: 900),

            padding: const EdgeInsets.all(35),

            decoration: BoxDecoration(
              color: Colors.white,

              borderRadius: BorderRadius.circular(24),

              border: Border.all(color: AppColors.border),

              boxShadow: [
                BoxShadow(
                  color: Colors.black.withOpacity(.05),

                  blurRadius: 25,

                  offset: const Offset(0, 8),
                ),
              ],
            ),

            child: Form(
              key: _formKey,

              child: Column(
                crossAxisAlignment: CrossAxisAlignment.start,

                children: [
                  _header(),

                  const SizedBox(height: 35),

                  _sectionTitle("Officer Information"),

                  GridView.count(
                    shrinkWrap: true,

                    physics: const NeverScrollableScrollPhysics(),

                    crossAxisCount: 2,

                    crossAxisSpacing: 20,

                    mainAxisSpacing: 20,

                    childAspectRatio: 4,

                    children: [
                      _input(
                        label: "Full Name",

                        controller: nameController,

                        icon: Icons.person,

                        required: true,
                      ),

                      _input(
                        label: "Phone Number",

                        controller: phoneController,

                        icon: Icons.phone,

                        keyboard: TextInputType.phone,

                        required: true,
                      ),

                      _input(
                        label: "National ID",

                        controller: nationalIdController,

                        icon: Icons.badge,
                      ),

                      _input(
                        label: "District",

                        controller: districtController,

                        icon: Icons.location_city,
                      ),
                    ],
                  ),

                  const SizedBox(height: 20),

                  _input(
                    label: "Address",

                    controller: addressController,

                    icon: Icons.home,

                    maxLines: 3,
                  ),

                  const SizedBox(height: 35),

                  SizedBox(
                    width: double.infinity,

                    height: 55,

                    child: ElevatedButton.icon(
                      onPressed: saving ? null : saveOfficer,

                      icon: saving
                          ? const SizedBox(
                              width: 20,

                              height: 20,

                              child: CircularProgressIndicator(
                                color: Colors.white,

                                strokeWidth: 2,
                              ),
                            )
                          : const Icon(Icons.save),

                      label: Text(
                        saving ? "SAVING..." : "SAVE OFFICER",

                        style: const TextStyle(
                          fontWeight: FontWeight.bold,

                          letterSpacing: .5,
                        ),
                      ),

                      style: ElevatedButton.styleFrom(
                        backgroundColor: AppColors.primaryBlue,

                        foregroundColor: Colors.white,

                        elevation: 0,

                        shape: RoundedRectangleBorder(
                          borderRadius: BorderRadius.circular(14),
                        ),
                      ),
                    ),
                  ),
                ],
              ),
            ),
          ),
        ),
      ),
    );
  }

  Widget _header() {
    return Row(
      children: [
        Container(
          padding: const EdgeInsets.all(14),

          decoration: BoxDecoration(
            color: AppColors.primaryBlue.withOpacity(.1),

            borderRadius: BorderRadius.circular(16),
          ),

          child: const Icon(
            Icons.badge_outlined,

            size: 35,

            color: AppColors.primaryBlue,
          ),
        ),

        const SizedBox(width: 15),

        const Column(
          crossAxisAlignment: CrossAxisAlignment.start,

          children: [
            Text(
              "Register Field Officer",

              style: TextStyle(
                fontSize: 26,

                fontWeight: FontWeight.bold,

                color: AppColors.textPrimary,
              ),
            ),

            SizedBox(height: 5),

            Text(
              "Create a new officer profile for loan collection management",

              style: TextStyle(color: AppColors.textSecondary),
            ),
          ],
        ),
      ],
    );
  }

  Widget _sectionTitle(String title) {
    return Text(
      title,

      style: const TextStyle(
        fontSize: 18,

        fontWeight: FontWeight.bold,

        color: AppColors.textPrimary,
      ),
    );
  }

  Widget _input({
    required String label,

    required TextEditingController controller,

    required IconData icon,

    TextInputType keyboard = TextInputType.text,

    int maxLines = 1,

    bool required = false,
  }) {
    return TextFormField(
      controller: controller,

      keyboardType: keyboard,

      maxLines: maxLines,

      validator: (value) {
        if (required && (value == null || value.trim().isEmpty)) {
          return "$label is required";
        }

        return null;
      },

      style: const TextStyle(
        color: AppColors.textPrimary,

        fontWeight: FontWeight.w500,
      ),

      decoration: InputDecoration(
        labelText: label,

        hintText: "Enter $label",

        prefixIcon: Icon(icon, color: AppColors.primaryBlue),

        filled: true,

        fillColor: AppColors.background,

        contentPadding: const EdgeInsets.symmetric(
          horizontal: 18,

          vertical: 18,
        ),

        border: OutlineInputBorder(
          borderRadius: BorderRadius.circular(14),

          borderSide: const BorderSide(color: AppColors.border),
        ),

        enabledBorder: OutlineInputBorder(
          borderRadius: BorderRadius.circular(14),

          borderSide: const BorderSide(color: AppColors.border),
        ),

        focusedBorder: OutlineInputBorder(
          borderRadius: BorderRadius.circular(14),

          borderSide: const BorderSide(color: AppColors.primaryBlue, width: 2),
        ),
      ),
    );
  }
}
