import 'package:flutter/material.dart';

import '../../../models/field_officer.dart';
import '../../../services/field_officer_service.dart';



class AddFieldOfficerScreen extends StatefulWidget {

  const AddFieldOfficerScreen({
    super.key,
  });


  @override
  State<AddFieldOfficerScreen> createState() =>
      _AddFieldOfficerScreenState();

}



class _AddFieldOfficerScreenState
    extends State<AddFieldOfficerScreen> {


  final _formKey =
      GlobalKey<FormState>();


  final FieldOfficerService _service =
      FieldOfficerService();



  final nameController =
      TextEditingController();


  final phoneController =
      TextEditingController();


  final nationalIdController =
      TextEditingController();


  final districtController =
      TextEditingController();


  final addressController =
      TextEditingController();



  bool saving = false;



  Future<void> saveOfficer() async {


    if(!_formKey.currentState!.validate()){
      return;
    }


    setState(() {
      saving = true;
    });



    try{


      final officer = FieldOfficer(

        // generated by service
        officerNumber: "",


        fullName:
        nameController.text.trim(),


        phone:
        phoneController.text.trim(),


        nationalId:
        nationalIdController.text.trim(),


        district:
        districtController.text.trim(),


        address:
        addressController.text.trim(),


        status:
        "ACTIVE",


        createdAt:
        DateTime.now()
            .toIso8601String(),


      );




      await _service.createFieldOfficer(
          officer
      );




      if(!mounted)return;



      ScaffoldMessenger.of(context)
          .showSnackBar(

        const SnackBar(

          content:
          Text(
            "Field officer created successfully",
          ),

        ),

      );



      Navigator.pop(context);



    }
    catch(e){


      ScaffoldMessenger.of(context)
          .showSnackBar(

        SnackBar(

          content:
          Text(
            e.toString(),
          ),

        ),

      );


    }
    finally{


      setState(() {
        saving=false;
      });


    }


  }







  @override
  Widget build(BuildContext context) {


    return Scaffold(

      appBar:
      AppBar(

        title:
        const Text(
          "Add Field Officer",
        ),

      ),



      body:
      SingleChildScrollView(

        padding:
        const EdgeInsets.all(16),


        child:
        Form(

          key:
          _formKey,


          child:
          Column(

            children: [


              TextFormField(

                controller:
                nameController,


                decoration:
                const InputDecoration(

                  labelText:
                  "Full Name",

                  prefixIcon:
                  Icon(Icons.person),

                  border:
                  OutlineInputBorder(),

                ),


                validator:(value){

                  if(value==null ||
                      value.trim().isEmpty){

                    return
                    "Enter full name";

                  }

                  return null;

                },

              ),




              const SizedBox(height:15),





              TextFormField(

                controller:
                phoneController,


                keyboardType:
                TextInputType.phone,


                decoration:
                const InputDecoration(

                  labelText:
                  "Phone Number",

                  prefixIcon:
                  Icon(Icons.phone),

                  border:
                  OutlineInputBorder(),

                ),


                validator:(value){


                  if(value==null ||
                      value.trim().isEmpty){

                    return
                    "Enter phone number";

                  }


                  return null;

                },


              ),




              const SizedBox(height:15),





              TextFormField(

                controller:
                nationalIdController,


                decoration:
                const InputDecoration(

                  labelText:
                  "National ID",

                  prefixIcon:
                  Icon(Icons.badge),

                  border:
                  OutlineInputBorder(),

                ),

              ),




              const SizedBox(height:15),





              TextFormField(

                controller:
                districtController,


                decoration:
                const InputDecoration(

                  labelText:
                  "District",

                  prefixIcon:
                  Icon(Icons.location_city),

                  border:
                  OutlineInputBorder(),

                ),

              ),





              const SizedBox(height:15),






              TextFormField(

                controller:
                addressController,


                maxLines:3,


                decoration:
                const InputDecoration(

                  labelText:
                  "Address",

                  prefixIcon:
                  Icon(Icons.home),

                  border:
                  OutlineInputBorder(),

                ),

              ),




              const SizedBox(height:30),




              SizedBox(

                width:
                double.infinity,


                height:
                50,


                child:
                ElevatedButton(

                  onPressed:
                  saving
                  ?
                  null
                  :
                  saveOfficer,


                  child:
                  saving

                  ?

                  const CircularProgressIndicator()

                  :

                  const Text(
                    "Save Officer",
                  ),

                ),

              )

            ],

          ),

        ),

      ),

    );

  }


}